### ISSUE TITLE
revisions

### ISSUE THREAD

**Issue by zenrabbit** [MarioZuliani/Sample-Protocol-January-2019#1]
convert to .csv so we can view in browser quick
Panoche with an e.

**Comment by zenrabbit** [comment]
ok got files.
- [x] rename Panoche throughout
- [x] why are there 4 sheets? etc is each a replicate? if so, put all in one
- [x] aggregate, have a rep column (I do not get where reps are), then convert to csv

**Comment by MarioZuliani** [comment]
4 sheets. Sheet 1 is the main bulk of the data. Sheet 2 is the meta-data file. Sheet 3 is data for the center of the microsite (the 20m site). Sheet 4 are extra samples we took that were not in sites but thought would be good to get some measurements to see how some of the shrubs have been doing since the last time they were measured.

Rep column added.

Converted to .csv
